// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "MarkdownEditor2022.2347dc70-1875-4775-bf48-f2b9fdfee8d4";
        public const string Name = "Markdown Editor v2";
        public const string Description = @"A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.";
        public const string Language = "en-US";
        public const string Version = "2.0.1003";
        public const string Author = "Mads Kristensen";
        public const string Tags = "markdown";
    }
}
