// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor2022
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MarkdownFileSelectedString = "288e3b08-3da7-4867-b227-b676b9e585c6";
        public static Guid MarkdownFileSelected = new Guid(MarkdownFileSelectedString);

        public const string EditorFactoryString = "24510b54-a648-4d69-a6c5-f68cbdf07546";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string MarkdownEditor2022String = "0b1dfe17-2eb2-4fcc-8054-b6ab002a579d";
        public static Guid MarkdownEditor2022 = new Guid(MarkdownEditor2022String);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MarkdownMenu = 0x0100;
        public const int MarkdownDocumentToolbar = 0x0200;
        public const int HeadingMenu = 0x0210;
        public const int EditorGroup = 0x0001;
        public const int ReferenceGroup = 0x0002;
        public const int SettingsGroup = 0x0003;
        public const int PreviewGroup = 0x0004;
        public const int ToolbarViewGroup = 0x0005;
        public const int ToolbarFormattingGroup = 0x0006;
        public const int ToolbarListGroup = 0x0007;
        public const int HeadingMenuGroup = 0x0008;
        public const int ToggleSync = 0x1000;
        public const int MakeBold = 0x1010;
        public const int MakeItalic = 0x1020;
        public const int InsertLink = 0x1030;
        public const int OpenSettings = 0x1040;
        public const int ShowKeybindings = 0x1050;
        public const int ShowMarkdownReference = 0x1060;
        public const int Refresh = 0x1070;
        public const int GenerateTOC = 0x1080;
        public const int TogglePreview = 0x1090;
        public const int ToggleSpellChecking = 0x1100;
        public const int GenerateHtml = 0x1110;
        public const int ExportToPdf = 0x1120;
        public const int CyclePreviewBackward = 0x1130;
        public const int ShowSource = 0x1140;
        public const int ShowSplit = 0x1150;
        public const int ShowPreview = 0x1160;
        public const int SetParagraph = 0x1170;
        public const int SetHeading1 = 0x1180;
        public const int SetHeading2 = 0x1190;
        public const int SetHeading3 = 0x11A0;
        public const int SetHeading4 = 0x11B0;
        public const int SetHeading5 = 0x11C0;
        public const int SetHeading6 = 0x11D0;
        public const int MakeStrikethrough = 0x11E0;
        public const int MakeHighlight = 0x11F0;
        public const int MakeSubscript = 0x1200;
        public const int MakeSuperscript = 0x1210;
        public const int MakeInlineCode = 0x1220;
        public const int MakeBulletList = 0x1230;
        public const int MakeNumberedList = 0x1240;
        public const int MakeTaskList = 0x1250;
    }
}
