// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownEditor2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "24510b54-a648-4d69-a6c5-f68cbdf07546";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string MarkdownEditor2022String = "0b1dfe17-2eb2-4fcc-8054-b6ab002a579d";
        public static Guid MarkdownEditor2022 = new Guid(MarkdownEditor2022String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorGroup = 0x0001;
        public const int ToggleSync = 0x1000;
        public const int MakeBold = 0x1010;
        public const int MakeItalic = 0x1020;
        public const int InsertLink = 0x1030;
    }
}